---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
spec:
  replicas: 7
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
      - name: blog-app
        image: behoyh/angular-firestore-kubernetes:0.1.2
        ports:
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: blog-app
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "new-cert"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 443
    name: https
    targetPort: 443
  - protocol: TCP
    port: 80
    name: http
    targetPort: 443
  selector:
    app: blog-app